/**
 * الملفات العلمية للمكملات — قاعدة بيانات قابلة للتوسع تعتمدها حاسبة المكملات.
 * كل ملف يحتوي شروط الأهلية والتحذيرات والحدود والمراجع.
 * محتوى تثقيفي تقديري فقط، وليس وصفات علاجية أو تشخيصًا.
 */
export interface SupplementProfile {
  key: string;
  nameAr: string;
  nameEn: string;
  scientificName: string;
  category: string;
  targetNutrient: string;
  trigger: 'nutrient' | 'training' | 'hydration' | 'lab' | 'none';
  descriptionAr: string;
  functionAr: string;
  consideredCasesAr: string;
  avoidGroupsAr: string;
  sideEffectsAr: string;
  naturalAlternativesAr: string;
  evidenceStrength: 'A' | 'B' | 'C' | 'D';
  minAge: number;
  suitableForMinors: boolean;
  needsLabTest: boolean;
  needsMedicalSupervision: boolean;
  needsRx: boolean;
  linkedToWeight: boolean;
  linkedToTraining: boolean;
  linkedToCompetition: boolean;
  doseUnit: string;
  minDose: number;
  maxDose: number;
  safeUpperLimit: number | null;
  timingAr: string;
  relationToMealsAr: string;
  durationDays: number | null;
  stopPeriodAr: string;
  medicationInteractionsAr: string;
  supplementInteractionsAr: string;
  contraindicationsAr: string;
  stopSymptomsAr: string;
  dopingRisk: 'none' | 'low' | 'medium' | 'high' | 'prohibited' | 'unknown';
  thirdPartyTestedRecommended: boolean;
  referencesAr: string;
  lastInfoUpdateYear: number;
}

export const SUPPLEMENT_PROFILES: SupplementProfile[] = [
  {
    key: 'whey',
    nameAr: 'بروتين مصل اللبن',
    nameEn: 'Whey Protein',
    scientificName: 'Whey Protein Isolate/Concentrate',
    category: 'بروتين',
    targetNutrient: 'protein',
    trigger: 'nutrient',
    descriptionAr: 'مصدر بروتيني سريع الامتصاص لدعم إصلاح العضلات بعد التدريب.',
    functionAr: 'يساعد في الوصول لهدف البروتين اليومي وسهولة الحمل والنقل.',
    consideredCasesAr: 'عند تعذر تغطية احتياج البروتين من الطعام أو بعد التدريبات المزدوجة.',
    avoidGroupsAr: 'حساسية الحليب، عدم تحمل اللاكتوز (استخدام معزول أو نباتي)، أمراض الكلى بإشراف طبيب.',
    sideEffectsAr: 'انتفاخ، غازات، اضطراب هضم عند البعض (خصوصًا اللاكتوز).',
    naturalAlternativesAr: 'زبادي يوناني، جبنة قريش، بيض، صدر دجاج، عدس، تونة.',
    evidenceStrength: 'A',
    minAge: 15,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: false,
    doseUnit: 'g',
    minDose: 20,
    maxDose: 40,
    safeUpperLimit: 60,
    timingAr: 'بعد التدريب أو عند الحاجة ضمن الوجبات',
    relationToMealsAr: 'يُفضَّل مع الطعام أو بعد الوجبة مباشرة.',
    durationDays: null,
    stopPeriodAr: 'يمكن التوقف دون مراحل تقليل عند تغطية الاحتياج غذائيًا.',
    medicationInteractionsAr: 'قد يتأثر امتصاص بعض الأدوية؛ فصل التوقيتات مع المضادات الحيوية.',
    supplementInteractionsAr: 'لا تداخل معروف؛ تجنب الإفراط مع مصادر البروتين الأخرى لتجنب عبء الكلى.',
    contraindicationsAr: 'أمراض الكلى، الحساسية للحليب.',
    stopSymptomsAr: 'انتفاخ مستمر، إسهال، طفح.',
    dopingRisk: 'low',
    thirdPartyTestedRecommended: true,
    referencesAr: 'ISSN Position Stand: Dietary protein for training adaptation.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'creatine',
    nameAr: 'كرياتين أحادي الهيدرات',
    nameEn: 'Creatine Monohydrate',
    scientificName: 'Creatine Monohydrate',
    category: 'قوة وأداء',
    targetNutrient: 'creatine',
    trigger: 'training',
    descriptionAr: 'من أكثر المكملات دراسةً لتحسين القوة والطاقة عالية الشدة القصيرة.',
    functionAr: 'يرفع مخزون الفوسفوكرياتين العضلي ويحسّن التسارع والسباقات القصيرة وقوة المقاومة.',
    consideredCasesAr: 'سباحون منافسون في مسافات 50-200م مع تدريب قوة منتظم.',
    avoidGroupsAr: 'القاصرون دون 18 (إلا بإشراف طبي صريح)، أمراض الكلى.',
    sideEffectsAr: 'احتباس سوائل خفيف، إزعاج معدي عند البعض.',
    naturalAlternativesAr: 'لحم بقري، سلمون، تونة.',
    evidenceStrength: 'A',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'g',
    minDose: 3,
    maxDose: 5,
    safeUpperLimit: 10,
    timingAr: 'بعد التدريب أو مع أي وجبة',
    relationToMealsAr: 'مع وجبة تحتوي كربوهيدرات/بروتين قد يحسّن الامتصاص.',
    durationDays: 30,
    stopPeriodAr: 'إعادة تقييم كل 8-12 أسبوع.',
    medicationInteractionsAr: 'يُحذر مع أدوية الكلى ومدرات البول.',
    supplementInteractionsAr: 'لا يُجمع مع كافيين بجرعات عالية حول التدريب لزيادة خطر الجفاف.',
    contraindicationsAr: 'أمراض الكلى.',
    stopSymptomsAr: 'غثيان، تشنج، تغير في البول.',
    dopingRisk: 'low',
    thirdPartyTestedRecommended: true,
    referencesAr: 'ISSN & International Society of Sports Nutrition 2017.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'caffeine',
    nameAr: 'كافيين',
    nameEn: 'Caffeine',
    scientificName: '1,3,7-Trimethylxanthine',
    category: 'قوة وأداء',
    targetNutrient: 'caffeine',
    trigger: 'training',
    descriptionAr: 'منشط طبيعي يحسّن اليقظة والأداء في التمارين متوسطة وعالية الشدة.',
    functionAr: 'يؤخر الإحساس بالتعب ويحسّن التركيز في سباقات متعددة أو جلسات صباحية.',
    consideredCasesAr: 'قبل جلسات التدريب أو صباح البطولة بجرعات معتدلة 1-3 ملجم/كجم.',
    avoidGroupsAr: 'القاصرون (تقييد شديد)، اضطرابات القلب والقلق، الحمل، الأرق.',
    sideEffectsAr: 'أرق، خفقان، قلق، جفاف، اضطراب نوم.',
    naturalAlternativesAr: 'قهوة سادة، شاي أخضر، نوم كافٍ.',
    evidenceStrength: 'A',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'mg',
    minDose: 100,
    maxDose: 300,
    safeUpperLimit: 400,
    timingAr: 'قبل التدريب بـ 30-60 دقيقة',
    relationToMealsAr: 'مع الطعام يخفف اضطراب المعدة.',
    durationDays: null,
    stopPeriodAr: 'تجنب المسائي قبل النوم بـ 8 ساعات.',
    medicationInteractionsAr: 'مع أدوية القلب والمنبهات ومضادات الاكتئاب.',
    supplementInteractionsAr: 'مع الكرياتين (بجرعات عالية) — مراقبة الترطيب.',
    contraindicationsAr: 'القلب، القلق، الحموضة، الحمل.',
    stopSymptomsAr: 'خفقان، أرق متكرر، قلق.',
    dopingRisk: 'low',
    thirdPartyTestedRecommended: false,
    referencesAr: 'ISSN 2019 & Australian Institute of Sport.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'beta-alanine',
    nameAr: 'بيتا ألانين',
    nameEn: 'Beta-Alanine',
    scientificName: 'Beta-Alanine',
    category: 'قوة وأداء',
    targetNutrient: 'beta-alanine',
    trigger: 'training',
    descriptionAr: 'حمض أميني يرفع كارنوزين العضلي ويؤخر التعب في الجهود عالية الشدة.',
    functionAr: 'يحسّن التحمل اللاهوائي في تكرارات السرعة (100-200م).',
    consideredCasesAr: 'تدريبات سرعة عالية الشدة متكررة مع تراكم لبنيك.',
    avoidGroupsAr: 'القاصرون، الحوامل/المرضعات، حساسية النياسين.',
    sideEffectsAr: 'وخز/تنميل جلدي مؤقت (Paresthesia) غير ضار.',
    naturalAlternativesAr: 'لحم بقري، دجاج، سلمون.',
    evidenceStrength: 'B',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'g',
    minDose: 3,
    maxDose: 5,
    safeUpperLimit: 6.4,
    timingAr: 'مع وجبة أو قبل التدريب',
    relationToMealsAr: 'مع الطعام يخفف الوخز.',
    durationDays: 28,
    stopPeriodAr: 'تحميل 4-6 أسابيع ثم صيانة.',
    medicationInteractionsAr: 'لا تداخل دوائي معروف.',
    supplementInteractionsAr: 'آمن مع الكرياتين.',
    contraindicationsAr: 'حساسية النياسين.',
    stopSymptomsAr: 'وخز مزعج مستمر.',
    dopingRisk: 'low',
    thirdPartyTestedRecommended: true,
    referencesAr: 'ISSN 2017.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'bicarbonate',
    nameAr: 'بيكربونات الصوديوم',
    nameEn: 'Sodium Bicarbonate',
    scientificName: 'NaHCO3',
    category: 'قوة وأداء',
    targetNutrient: 'bicarbonate',
    trigger: 'training',
    descriptionAr: 'مخزن خارجي يساعد في مقاومة الحموضة أثناء الجهود اللاهوائية المكثفة.',
    functionAr: 'يحسّن الأداء في السباقات القصيرة والمتوسطة بامتصاص حمض اللبنيك.',
    consideredCasesAr: 'سباقات 200-400م مع تدريب مسبق لتحمّل الأعراض الهضمية.',
    avoidGroupsAr: 'اضطرابات المعدة والكلى، ارتفاع ضغط الدم، القاصرون.',
    sideEffectsAr: 'اضطراب معدة، انتفاخ، إسهال.',
    naturalAlternativesAr: 'لا بديل غذائي مباشر — يُجرَّب في التدريب فقط قبل البطولة.',
    evidenceStrength: 'B',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'g',
    minDose: 0.2,
    maxDose: 0.3,
    safeUpperLimit: 0.4,
    timingAr: 'قبل السباق بـ 60-90 دقيقة',
    relationToMealsAr: 'مع وجبة خفيفة للتقليل من الاضطراب الهضمي.',
    durationDays: null,
    stopPeriodAr: 'لا يُستخدم يوميًا لفترات طويلة.',
    medicationInteractionsAr: 'مميعات الدم، أدوية الضغط.',
    supplementInteractionsAr: 'تجنب مع الصوديوم الإضافي لتجاوز الحد الأعلى.',
    contraindicationsAr: 'اضطرابات المعدة والكلى.',
    stopSymptomsAr: 'إسهال حاد، ألم معدة.',
    dopingRisk: 'medium',
    thirdPartyTestedRecommended: true,
    referencesAr: 'AIS & ISSN; يلزم اختباره في التدريب قبل البطولة.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'nitrate',
    nameAr: 'نترات/عصير الشمندر',
    nameEn: 'Beetroot / Nitrate',
    scientificName: 'Dietary Nitrate (NO3-)',
    category: 'قوة وأداء',
    targetNutrient: 'nitrate',
    trigger: 'training',
    descriptionAr: 'يحسّن كفاءة الأكسجين في الجهود متوسطة الشدة عبر أكسيد النيتريك.',
    functionAr: 'يحسّن الكفاءة الهوائية ويقلل كلفة الأكسجين في جلسات التحمل.',
    consideredCasesAr: 'تدريبات التحمل والمجموعات الإضافية (أفضل من خلال الشمندر).',
    avoidGroupsAr: 'أصحاب الضغط المنخفض، الحوامل، مرضى الكلى.',
    sideEffectsAr: 'تغير لون البول، اضطراب معدة.',
    naturalAlternativesAr: 'عصير شمندر، سبانخ، خضار ورقية (الغذاء أولًا).',
    evidenceStrength: 'B',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'ml',
    minDose: 300,
    maxDose: 500,
    safeUpperLimit: null,
    timingAr: 'قبل التدريب بـ 2-3 ساعات',
    relationToMealsAr: 'مع الطعام أو منفصلًا.',
    durationDays: null,
    stopPeriodAr: 'البدء قبل البطولة بعدة أسابيع للتحميل.',
    medicationInteractionsAr: 'أدوية الضغط.',
    supplementInteractionsAr: 'لا تداخل معروف.',
    contraindicationsAr: 'الضغط المنخفض.',
    stopSymptomsAr: 'هبوط ضغط.',
    dopingRisk: 'low',
    thirdPartyTestedRecommended: false,
    referencesAr: 'AIS — الغذاء أولًا.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'carb-drink',
    nameAr: 'مشروب كربوهيدرات',
    nameEn: 'Carbohydrate Sports Drink',
    scientificName: 'Maltodextrin + Sugars',
    category: 'أداء وتحمل',
    targetNutrient: 'carbs',
    trigger: 'training',
    descriptionAr: 'وقود سريع للجلسات الطويلة (أكثر من 60-75 دقيقة).',
    functionAr: 'يحافظ على مستوى الجليكوجين ويؤخر هبوط الأداء.',
    consideredCasesAr: 'تدريبات طويلة أو مزدوجة أو أيام سباقات متعددة.',
    avoidGroupsAr: 'السكري، الحساسية للمكونات.',
    sideEffectsAr: 'اضطراب معدة عند التركيز العالي.',
    naturalAlternativesAr: 'موز، تمر، عسل، عصير فواكه.',
    evidenceStrength: 'A',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'g',
    minDose: 30,
    maxDose: 60,
    safeUpperLimit: 90,
    timingAr: 'أثناء التدريب الطويل',
    relationToMealsAr: 'قبل وأثناء الجلسة حسب الحاجة.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'السكري.',
    supplementInteractionsAr: 'مع إلكتروليت أثناء الجلسة.',
    contraindicationsAr: 'السكري.',
    stopSymptomsAr: 'اضطراب معدة.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'AIS Sports Drinks.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'electrolytes',
    nameAr: 'إلكتروليت (صوديوم/بوتاسيوم)',
    nameEn: 'Electrolytes',
    scientificName: 'Sodium + Potassium + Magnesium',
    category: 'ترطيب',
    targetNutrient: 'sodium',
    trigger: 'hydration',
    descriptionAr: 'تعويض المعادن المفقودة بالتعرق في الجلسات الطويلة أو الحرارة.',
    functionAr: 'يمنع التشنجات ويحافظ على الترطيب والإشارات العصبية.',
    consideredCasesAr: 'جلسات أكثر من 60-75 دقيقة أو حرارة مرتفعة أو تعرق غزير.',
    avoidGroupsAr: 'مرضى الضغط والكلى (تقييد الصوديوم) — تحت إشراف طبي.',
    sideEffectsAr: 'عطش، احتباس سوائل.',
    naturalAlternativesAr: 'موز، تمر، ماء مملح قليلًا بعد الجلسة.',
    evidenceStrength: 'B',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: true,
    linkedToCompetition: true,
    doseUnit: 'mg',
    minDose: 300,
    maxDose: 1000,
    safeUpperLimit: 2300,
    timingAr: 'قبل/أثناء/بعد الجلسة حسب التعرق',
    relationToMealsAr: 'مع السوائل أثناء التدريب.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'أدوية الضغط ومدرات البول.',
    supplementInteractionsAr: 'تجنب تكرار الصوديوم من منتجات متعددة.',
    contraindicationsAr: 'الضغط المرتفع، الفشل الكلوي.',
    stopSymptomsAr: 'اضطراب معدة.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'AIS Hydration.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'vitamin-d',
    nameAr: 'فيتامين د',
    nameEn: 'Vitamin D',
    scientificName: 'Cholecalciferol (D3)',
    category: 'فيتامينات',
    targetNutrient: 'vitaminD',
    trigger: 'lab',
    descriptionAr: 'ضروري لصحة العظام والمناعة والأداء، ويقل لدى سباحي التدريب الداخلي.',
    functionAr: 'يدعم قوة العظام والمناعة والاستشفاء وتوازن الهرمونات.',
    consideredCasesAr: 'نقص مثبت بتحليل الدم (25-OH-D) أو قلة شمس وتدريب داخلي مكثف.',
    avoidGroupsAr: 'لا تُعطَ جرعات عالية دون تحليل — التسمم وارد.',
    sideEffectsAr: 'فرط كالسيوم، غثيان مع الجرعات الزائدة.',
    naturalAlternativesAr: 'الشمس، أسماك دهنية، حليب مدعم.',
    evidenceStrength: 'A',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: true,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'IU',
    minDose: 600,
    maxDose: 2000,
    safeUpperLimit: 4000,
    timingAr: 'مع وجبة تحتوي دهون',
    relationToMealsAr: 'مع الطعام لامتصاص أفضل.',
    durationDays: 90,
    stopPeriodAr: 'إعادة تحليل بعد 3 أشهر.',
    medicationInteractionsAr: 'أدوية الكورتيزون وبعض أدوية القلب.',
    supplementInteractionsAr: 'مع الكالسيوم بجرعات عالية — مراقبة فرط الكالسيوم.',
    contraindicationsAr: 'الساركويد، فرط كالسيوم.',
    stopSymptomsAr: 'غثيان، إمساك، ضعف.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'Endocrine Society guidelines.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'iron',
    nameAr: 'حديد',
    nameEn: 'Iron',
    scientificName: 'Ferrous Sulfate / Iron',
    category: 'معادن',
    targetNutrient: 'iron',
    trigger: 'lab',
    descriptionAr: 'أساسي لنقل الأكسجين؛ نقصه شائع لدى السباحات والمراهقين.',
    functionAr: 'يحسّن الهيموجلوبين وقدرة التحمل عند نقص مثبت.',
    consideredCasesAr: 'نقص مثبت بالتحاليل (فيريتين/هيموجلوبين) بإشراف طبي حصري.',
    avoidGroupsAr: 'لا يُعطى دون نقص — خطر فرط الحديد.',
    sideEffectsAr: 'إمساك، غثيان، تلون البراز.',
    naturalAlternativesAr: 'لحوم حمراء، سبانخ مع فيتامين C، بقوليات.',
    evidenceStrength: 'A',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: true,
    needsMedicalSupervision: true,
    needsRx: true,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mg',
    minDose: 15,
    maxDose: 65,
    safeUpperLimit: 45,
    timingAr: 'على معدة فارغة أو مع فيتامين C',
    relationToMealsAr: 'يُفصل عن الكالسيوم والشاي والقهوة.',
    durationDays: 90,
    stopPeriodAr: 'إعادة تحليل دورية — لا تستمر دون متابعة.',
    medicationInteractionsAr: 'مضادات الحموضة، بعض المضادات الحيوية.',
    supplementInteractionsAr: 'تجنب الجمع مع الكالسيوم في نفس الوقت.',
    contraindicationsAr: 'الهيموكروماتوز، أمراض الكبد.',
    stopSymptomsAr: 'إمساك شديد.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'اللجنة الأولمبية — فحص دوري للرياضيات.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'calcium',
    nameAr: 'كالسيوم',
    nameEn: 'Calcium',
    scientificName: 'Calcium Carbonate/Citrate',
    category: 'معادن',
    targetNutrient: 'calcium',
    trigger: 'lab',
    descriptionAr: 'معدن أساسي لصحة العظام وتقلص العضلات، مهم في سن النمو.',
    functionAr: 'يدعم كثافة العظام ومنع الكسور الإجهادية.',
    consideredCasesAr: 'عند نقص مدخول الألبان أو نقص مثبت بالتحليل.',
    avoidGroupsAr: 'فرط كالسيوم، حصوات الكلى.',
    sideEffectsAr: 'إمساك، غازات.',
    naturalAlternativesAr: 'حليب، زبادي، جبن، خضار ورقية، تين.',
    evidenceStrength: 'A',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mg',
    minDose: 500,
    maxDose: 1000,
    safeUpperLimit: 2500,
    timingAr: 'مع وجبة، على دفعتين',
    relationToMealsAr: 'مع الطعام لامتصاص أفضل.',
    durationDays: null,
    stopPeriodAr: 'مراجعة دورية.',
    medicationInteractionsAr: 'مضادات حيوية (تتراسايكلين) — افصل التوقيت.',
    supplementInteractionsAr: 'لا يُجمع مع الحديد في نفس الوقت.',
    contraindicationsAr: 'فرط كالسيوم.',
    stopSymptomsAr: 'إمساك شديد.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'NIH ODS.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'magnesium',
    nameAr: 'مغنيسيوم',
    nameEn: 'Magnesium',
    scientificName: 'Magnesium Citrate/Glycinate',
    category: 'معادن',
    targetNutrient: 'magnesium',
    trigger: 'lab',
    descriptionAr: 'معدن أساسي لوظائف العضلات والأعصاب وجودة النوم، يُفقد بالتعرق.',
    functionAr: 'يخفف التشنجات ويدعم النوم والاستشفاء.',
    consideredCasesAr: 'تشنجات متكررة، صعوبة نوم، تعرق غزير منتظم.',
    avoidGroupsAr: 'الفشل الكلوي الحاد.',
    sideEffectsAr: 'إسهال عند الجرعات العالية.',
    naturalAlternativesAr: 'مكسرات، بذور، سبانخ، حبوب كاملة، موز.',
    evidenceStrength: 'B',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mg',
    minDose: 200,
    maxDose: 400,
    safeUpperLimit: 350,
    timingAr: 'مساءً قبل النوم',
    relationToMealsAr: 'مع الطعام لتجنب اضطراب المعدة.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'بعض المضادات الحيوية وأدوية العظام — افصل التوقيت.',
    supplementInteractionsAr: 'مع الزنك بجرعات عالية تنافس على الامتصاص.',
    contraindicationsAr: 'الفشل الكلوي.',
    stopSymptomsAr: 'إسهال مستمر.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'NIH ODS.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'zinc',
    nameAr: 'زنك',
    nameEn: 'Zinc',
    scientificName: 'Zinc Gluconate/Picolinate',
    category: 'معادن',
    targetNutrient: 'zinc',
    trigger: 'lab',
    descriptionAr: 'يدعم المناعة والاستشفاء والتئام الأنسجة.',
    functionAr: 'يدعم المناعة والهرمونات والاستشفاء عند نقص.',
    consideredCasesAr: 'نقص مثبت أو نظام نباتي صارم بدون مصادر كافية.',
    avoidGroupsAr: 'جرعات عالية طويلة (تسبب نقص نحاس).',
    sideEffectsAr: 'غثيان، طعم معدني.',
    naturalAlternativesAr: 'لحوم، مأكولات بحرية، مكسرات، بقوليات.',
    evidenceStrength: 'B',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: true,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mg',
    minDose: 8,
    maxDose: 15,
    safeUpperLimit: 40,
    timingAr: 'مع وجبة',
    relationToMealsAr: 'لا يُؤخذ مع الحديد/الكالسيوم معًا.',
    durationDays: 60,
    stopPeriodAr: 'إعادة تقييم.',
    medicationInteractionsAr: 'المضادات الحيوية.',
    supplementInteractionsAr: 'مع المغنيسيوم بجرعات عالية.',
    contraindicationsAr: 'لا.',
    stopSymptomsAr: 'غثيان مستمر.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'NIH ODS.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'vitamin-b12',
    nameAr: 'فيتامين ب12',
    nameEn: 'Vitamin B12',
    scientificName: 'Cyanocobalamin / Methylcobalamin',
    category: 'فيتامينات',
    targetNutrient: 'b12',
    trigger: 'lab',
    descriptionAr: 'أساسي لتكوين الدم والأعصاب والطاقة؛ شائع نقصه لدى النباتيين.',
    functionAr: 'يدعم إنتاج الطاقة وتكوين خلايا الدم الحمراء.',
    consideredCasesAr: 'نظام نباتي صارم أو نقص مثبت بالتحليل.',
    avoidGroupsAr: 'لا موانع كبيرة بجرعات معتدلة.',
    sideEffectsAr: 'نادرة.',
    naturalAlternativesAr: 'لحوم، أسماك، ألبان، بيض.',
    evidenceStrength: 'A',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: true,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mcg',
    minDose: 2.4,
    maxDose: 25,
    safeUpperLimit: null,
    timingAr: 'مع وجبة',
    relationToMealsAr: 'أي وقت.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'ميتفورمين يخفض الامتصاص.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'لا.',
    stopSymptomsAr: 'لا.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'NIH ODS.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'folate',
    nameAr: 'حمض الفوليك',
    nameEn: 'Folate / Folic Acid',
    scientificName: 'Vitamin B9',
    category: 'فيتامينات',
    targetNutrient: 'folate',
    trigger: 'lab',
    descriptionAr: 'أساسي لتكوين خلايا الدم والنمو؛ مهم للمراهقات والرياضيات.',
    functionAr: 'يدعم تكوين خلايا الدم الحمراء والتعافي.',
    consideredCasesAr: 'نقص مثبت أو نظام غذائي مقيد.',
    avoidGroupsAr: 'لا.',
    sideEffectsAr: 'نادرة.',
    naturalAlternativesAr: 'خضار ورقية، بقوليات، حبوب كاملة.',
    evidenceStrength: 'A',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: true,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mcg',
    minDose: 200,
    maxDose: 400,
    safeUpperLimit: 1000,
    timingAr: 'مع وجبة',
    relationToMealsAr: 'مع الطعام.',
    durationDays: 60,
    stopPeriodAr: 'إعادة تقييم.',
    medicationInteractionsAr: 'بعض أدوية الصرع.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'لا.',
    stopSymptomsAr: 'لا.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'NIH ODS.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'vitamin-c',
    nameAr: 'فيتامين سي',
    nameEn: 'Vitamin C',
    scientificName: 'Ascorbic Acid',
    category: 'فيتامينات',
    targetNutrient: 'vitaminC',
    trigger: 'lab',
    descriptionAr: 'مضاد أكسدة ويدعم المناعة وامتصاص الحديد.',
    functionAr: 'يدعم المناعة وتقليل الإجهاد التأكسدي مع التدريب المكثف.',
    consideredCasesAr: 'نظام غذائي فقير بالخضار والفواكه أو إجهاد تدريبي مرتفع.',
    avoidGroupsAr: 'لا.',
    sideEffectsAr: 'إسهال بجرعات عالية جدًا.',
    naturalAlternativesAr: 'حمضيات، كيوي، فلفل، فراولة.',
    evidenceStrength: 'B',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'mg',
    minDose: 100,
    maxDose: 500,
    safeUpperLimit: 2000,
    timingAr: 'مع وجبة',
    relationToMealsAr: 'يحسّن امتصاص الحديد.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'لا.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'لا.',
    stopSymptomsAr: 'إسهال.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: false,
    referencesAr: 'NIH ODS.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'omega3',
    nameAr: 'أوميجا-3',
    nameEn: 'Omega-3 (EPA/DHA)',
    scientificName: 'Eicosapentaenoic/Docosahexaenoic Acid',
    category: 'صحة واستشفاء',
    targetNutrient: 'omega3',
    trigger: 'nutrient',
    descriptionAr: 'أحماض دهنية مهمة للالتهاب وصحة القلب والمفاصل والاستشفاء.',
    functionAr: 'يقلل الالتهاب الخفيف ويدعم صحة المفاصل والقلب في المواسم المكثفة.',
    consideredCasesAr: 'عدم انتظام تناول أسماك دهنية أو تدريب مكثف.',
    avoidGroupsAr: 'مميعات الدم، حساسية الأسماك، قبل العمليات.',
    sideEffectsAr: 'تجشؤ، طعم سمكي.',
    naturalAlternativesAr: 'سلمون، تونة، ماكريل، بذور الكتان.',
    evidenceStrength: 'B',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'g',
    minDose: 1,
    maxDose: 3,
    safeUpperLimit: 5,
    timingAr: 'مع وجبة تحتوي دهون',
    relationToMealsAr: 'مع الطعام.',
    durationDays: null,
    stopPeriodAr: 'التوقف قبل العمليات بأسبوعين.',
    medicationInteractionsAr: 'مميعات الدم.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'حساسية الأسماك.',
    stopSymptomsAr: 'نزيف، كدمات.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: true,
    referencesAr: 'AIS Fish Oil.',
    lastInfoUpdateYear: 2023,
  },
  {
    key: 'probiotics',
    nameAr: 'بروبيوتيك',
    nameEn: 'Probiotics',
    scientificName: 'Lactobacillus / Bifidobacterium',
    category: 'صحة هضمية',
    targetNutrient: 'probiotics',
    trigger: 'none',
    descriptionAr: 'بكتيريا نافعة تدعم صحة الجهاز الهضمي والمناعة.',
    functionAr: 'يدعم صحة الأمعاء والمناعة خاصة في المواسم الطويلة والسفر.',
    consideredCasesAr: 'اضطرابات هضمية متكررة أو بعد مضادات حيوية.',
    avoidGroupsAr: 'نقص المناعة الشديد.',
    sideEffectsAr: 'غازات أولية.',
    naturalAlternativesAr: 'زبادي، لبن رايب، مخلالات.',
    evidenceStrength: 'B',
    minAge: 14,
    suitableForMinors: true,
    needsLabTest: false,
    needsMedicalSupervision: false,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'CFU',
    minDose: 1,
    maxDose: 10,
    safeUpperLimit: null,
    timingAr: 'مع وجبة أو قبل النوم',
    relationToMealsAr: 'مع الطعام.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'لا.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'نقص المناعة.',
    stopSymptomsAr: 'إسهال مستمر.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: true,
    referencesAr: 'ISSFAL/ISSN.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'collagen',
    nameAr: 'كولاجين',
    nameEn: 'Collagen / Gelatin',
    scientificName: 'Hydrolyzed Collagen',
    category: 'صحة المفاصل',
    targetNutrient: 'collagen',
    trigger: 'none',
    descriptionAr: 'بروتين هيكلي قد يدعم صحة الأوتار والمفاصل.',
    functionAr: 'دعم محتمل لصحة المفاصل والاستشفاء من الإصابات.',
    consideredCasesAr: 'ألم مفاصل خفيف متكرر (بعد استبعاد إصابة).',
    avoidGroupsAr: 'لا.',
    sideEffectsAr: 'نادرة.',
    naturalAlternativesAr: 'مرق العظام، أغذية غنية بالبروتين والفيتامين C.',
    evidenceStrength: 'C',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'g',
    minDose: 5,
    maxDose: 15,
    safeUpperLimit: null,
    timingAr: 'قبل النوم أو مع وجبة',
    relationToMealsAr: 'مع فيتامين C لتحسين التخليق.',
    durationDays: 90,
    stopPeriodAr: 'مراجعة بعد 3 أشهر.',
    medicationInteractionsAr: 'لا.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'لا.',
    stopSymptomsAr: 'لا.',
    dopingRisk: 'none',
    thirdPartyTestedRecommended: true,
    referencesAr: 'أدلة محدودة — درجة C.',
    lastInfoUpdateYear: 2022,
  },
  {
    key: 'meal-replacement',
    nameAr: 'بديل وجبة',
    nameEn: 'Meal Replacement',
    scientificName: 'Balanced meal powder',
    category: 'وجبات',
    targetNutrient: 'calories',
    trigger: 'nutrient',
    descriptionAr: 'مزيج بروتين وكربوهيدرات ودهون وفيتامينات لوجبة سريعة.',
    functionAr: 'وجبة عملية عند ضيق الوقت أو سفر — ليس بديلًا دائمًا عن الطعام.',
    consideredCasesAr: 'جدول مزدحم يمنع وجبات منتظمة.',
    avoidGroupsAr: 'لا.',
    sideEffectsAr: 'اضطراب معدة عند البعض.',
    naturalAlternativesAr: 'وجبات حقيقية متوازنة — الغذاء أولًا.',
    evidenceStrength: 'C',
    minAge: 18,
    suitableForMinors: false,
    needsLabTest: false,
    needsMedicalSupervision: true,
    needsRx: false,
    linkedToWeight: false,
    linkedToTraining: false,
    linkedToCompetition: false,
    doseUnit: 'scoop',
    minDose: 1,
    maxDose: 2,
    safeUpperLimit: null,
    timingAr: 'كوجبة عند الحاجة',
    relationToMealsAr: 'وجبة كاملة.',
    durationDays: null,
    stopPeriodAr: 'لا.',
    medicationInteractionsAr: 'لا.',
    supplementInteractionsAr: 'لا.',
    contraindicationsAr: 'لا.',
    stopSymptomsAr: 'لا.',
    dopingRisk: 'medium',
    thirdPartyTestedRecommended: true,
    referencesAr: 'AIS — الغذاء أولًا.',
    lastInfoUpdateYear: 2022,
  },
];

export const profileByKey = (key: string): SupplementProfile | undefined =>
  SUPPLEMENT_PROFILES.find((p) => p.key === key);

export const categoryName = (c: string): string =>
  c === 'بروتين' ? 'بروتين' : c === 'قوة وأداء' ? 'قوة وأداء' : c === 'ترطيب' ? 'ترطيب' : c === 'فيتامينات' ? 'فيتامينات' : c === 'معادن' ? 'معادن' : c === 'صحة واستشفاء' ? 'صحة واستشفاء' : c;
